version: "2.1"

volumes:
  config:

services:
  homeassistant:
    image: homeassistant/aarch64-homeassistant:2025.2.5
    container_name: hass-serve
    ports:
      - '80:8123'
    devices:
      - /dev/ttyAMA0:/dev/ttyAMA0
      - /dev/vcio:/dev/vcio
    restart: always
    volumes:
      - config:/config
      - /run/dbus:/run/dbus:ro
      # - /etc/localtime:/etc/localtime:ro
    privileged: true
    environment:
      TZ: America/New_York
    network_mode: host

  hass-configurator:
    image: causticlab/hass-configurator-docker:0.5.2@sha256:ec2002abf216f64a6f0927c12032356141b8bb0e5b40e0e43fec3511df4e02b4
    container_name: hassconf-serve
    restart: unless-stopped
    ports:
      - "8080:3218/tcp"
    volumes:
      - config:/hass-config
    environment:
      - HC_BASEPATH=/hass-config
    depends_on:
      - homeassistant
  mqtt:
    image: arm64v8/eclipse-mosquitto:2.0.20
    container_name: mqtt-bridge
    ports:
      - "1883:1883"
    depends_on:
      - homeassistant
