version: "2.1"

volumes:
  config:

services:
  homeassistant:
    image: homeassistant/raspberrypi4-64-homeassistant:2021.7.2
    restart: always
    privileged: true
    ports:
      - "80:8123"
    volumes:
      - "config:/config"
    devices:
      - "/dev:/dev"
      - "/dev/serial/by-id/usb-0658_0200-if00:/dev/zwave"
      - "/dev/ttyAMA0:/dev/ttyAMA0"
  hass-configurator:
    platform: linux/arm64
    image: causticlab/hass-configurator-docker:0.4.1
    restart: unless-stopped
    ports:
      - "3218:3218/tcp"
    volumes:
      - "config:/hass-config"
    environment:
      - HC_BASEPATH=/hass-config
  mqtt:
    image: arm64v8/eclipse-mosquitto:2.0
    restart: unless-stopped
    ports:
      - "1883:1883"
